apiVersion: v1
kind: Secret
metadata:
  name: nats-credentials
  labels:
    app: nats
type: Opaque
data:
  region: RWFzdA== # Base64 encoded value of "East"
  nats-servers: bmF0czovL25hdHMtZWFzdC5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjQyMjI= # Base64 encoded value of "nats://nats-east.default.svc.cluster.local:4222"