# Root CA and TLS certs for NATS
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigning
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-ca
spec:
  secretName: nats-ca
  duration: 8736h # 1 year
  renewBefore: 240h # 10 days
  issuerRef:
    name: selfsigning
    kind: ClusterIssuer
  commonName: nats-ca
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nats-ca
spec:
  ca:
    secretName: nats-ca
---
# NATS server TLS certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-server-tls
spec:
  secretName: nats-server-tls
  duration: 2160h # 90 days
  renewBefore: 240h # 10 days
  issuerRef:
    name: nats-ca
    kind: Issuer
  commonName: nats-east.default.svc.cluster.local
  dnsNames:
  - nats-east
  - nats-east.default
  - nats-east.default.svc
  - nats-east.default.svc.cluster.local
  - '*.nats-east'
  - '*.nats-east.default'
  - '*.nats-east.default.svc'
  - '*.nats-east.default.svc.cluster.local'
  - 'k8s-default-natseast-d3a2cc2411-682b3011270d1d56.elb.us-east-1.amazonaws.com'
---
# NATS system user TLS certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-sys-tls
spec:
  secretName: nats-sys-tls
  duration: 2160h # 90 days
  renewBefore: 240h # 10 days
  issuerRef:
    name: nats-ca
    kind: Issuer
  usages:
    - digital signature
    - key encipherment
    - client auth
  commonName: nats-sys-user
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-admin-tls
spec:
  secretName: nats-admin-tls
  duration: 2160h # 90 days
  renewBefore: 240h # 10 days
  issuerRef:
    name: nats-ca
    kind: Issuer
  usages:
    - digital signature
    - key encipherment
    - client auth
  commonName: nats-admin
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-operator-tls
spec:
  secretName: nats-operator-tls
  duration: 2160h # 90 days
  renewBefore: 240h # 10 days
  issuerRef:
    name: nats-ca
    kind: Issuer
  usages:
    - digital signature
    - key encipherment
    - client auth
  commonName: nats-operator
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-requester-tls
spec:
  secretName: nats-requester-tls
  duration: 2160h # 90 days
  renewBefore: 240h # 10 days
  issuerRef:
    name: nats-ca
    kind: Issuer
  usages:
    - digital signature
    - key encipherment
    - client auth
  commonName: nats-requester
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-recorder-tls
spec:
  secretName: nats-recorder-tls
  duration: 2160h # 90 days
  renewBefore: 240h # 10 days
  issuerRef:
    name: nats-ca
    kind: Issuer
  usages:
    - digital signature
    - key encipherment
    - client auth
  commonName: nats-recorder