tlsCA:
  enabled: true
  secretName: nats-sys-tls
  key: ca.crt

config:
  # this tells the NATS server to use the K8s service for the client connection
  client_advertise: "nats://nats-west.default.svc.cluster.local:4222"
  nats:
    tls:
      enabled: true
      secretName: nats-server-tls
      cert: tls.crt
      key: tls.key
      merge:
        verify_and_map: true
  cluster:
    enabled: true
    replicas: 3
  jetstream:
    enabled: true
    domain: "nats-cloud"
    fileStore:
      pvc:
        size: 10Gi
  leafnodes:
    enabled: true
    authorization:
      user: natsleaf
      password: NATSC!u5t3rL3afn0d3
  gateway:
    # NOTE: the gateway name must match the Helm release name
    # so if you run `helm install nats-west ...` the gateway name must be `nats-west`
    name: "nats-west"
    enabled: true
    merge:
      # populate with your NATS server address in Azure
      advertise: ""
      authorization:
        user: natsgate
        password: NATSC!u5t3rGa73way
      # for this demo, I used the cloud provider's load balancer servicer.
      # that means I had to wait for the load balancer to be created before I knew
      # what the external IP address was. until then, the following two lines were
      # commented out. once the load balancer was created, I uncommented them
      # and updated the values entries with the correct endpoints.
      gateways: 
      - name: "nats-east"
        # populate with your NATS server address in EKS
        url: ""
      - name: "nats-west"
        # populate with your NATS server address in Azure
        url: ""
  merge:
    accounts:
      SYS:
        users:
          - user: CN=nats-sys-user
          - user: sys
            pass: sysuser
      # primary account that was used to deploy the services in this demo
      teamA:
        jetstream: enabled
        users:
          - user: CN=nats-admin
            permissions:
              publish:
                allow: 
                - ">"
              subscribe:
                allow: 
                - ">"
          # the four math operator services used this user
          - user: CN=nats-operator
            permissions:
              publish:
                allow: "$SRV.>"
              subscribe:
                allow: 
                - "$SRV.>" # necessary for service metrics
                - "math.numbers.>"
                - "_INBOX.>" # necessary for responses
              allow_responses: true
          # the requester job used this user
          - user: CN=nats-requester
            permissions:
              publish:
                allow: 
                - "math.numbers.>"
                - "answers.*"
              subscribe:
                allow: 
                - "_INBOX.>" # necessary for responses
          # the recorder service that stuffs it all into MySQL
          - user: CN=nats-recorder
            permissions:
              subscribe:
                allow: 
                - "answers.*"
                - "_INBOX.>" 
    system_account: SYS

podTemplate:
  topologySpreadConstraints:
    kubernetes.io/hostname:
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule

# this block configures the K8s service to use the Azure load balancer
service:
  ports:
    gateway:
      enabled: true
  merge:
    metadata:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    spec:
      type: LoadBalancer
      publishNotReadyAddresses: true
      ports:
        - name: nats
          port: 4222
          targetPort: 4222
        - name: gateway
          port: 7222
          targetPort: 7222


