apiVersion: batch/v1
kind: Job
metadata:
  name: requester
  labels:
    app: requester
spec:
  template:
    metadata:
      labels:
        app: requester
    spec:
      volumes:
        - name: nats-requester-tls
          secret:
            secretName: nats-requester-tls
      containers:
        - name: requester
          image: ghcr.io/colinjlacy/colinjlacy/nats-jetstream-demo-requester:latest
          imagePullPolicy: Always
          env:
            - name: NATS_SERVERS
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: nats-servers
            - name: LOOP_COUNT
              value: "10"
          volumeMounts:
            - name: nats-requester-tls
              mountPath: /etc/nats/tls
              readOnly: true
      restartPolicy: Never
  backoffLimit: 4