apiVersion: apps/v1
kind: Deployment
metadata:
  name: subtractor-deployment
  labels:
    app: subtractor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: subtractor
  template:
    metadata:
      labels:
        app: subtractor
    spec:
      volumes:
        - name: nats-operator-tls
          secret:
            secretName: nats-operator-tls
      containers:
        - name: subtractor
          image: ghcr.io/colinjlacy/colinjlacy/nats-cluster-demo-subtractor:latest
          imagePullPolicy: Always
          env:
            - name: NATS_SERVERS
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: nats-servers
            - name: REGION 
              valueFrom:
                secretKeyRef:
                  name: nats-credentials
                  key: region
          volumeMounts:
            - name: nats-operator-tls
              mountPath: /etc/nats/tls
              readOnly: true
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "250m"